fix registration api tests
appsembler/edx-platform pull request #1030
Opened 2021-10-07 20:43 UTC by estherjsuh

## Fix tests for Registration API

I found some typos in the assert statement introduced by a previous [PR](https://github.com/appsembler/edx-platform/commit/c5157b1f74a4c3a4f085ae0ca43e9b70d7efc759#diff-44335d85d2ecfa71a895772a18d1bb7ac5c9441a71cbbac865062f00b76d9739).

Update assertion to **not** send activation email by updating:
-   `send_activation_email` is `[True, 'True', 'true']` ➡️  `send_activation_email` is `[False, 'False', 'false']`

Beeline tracing added to debug issue added in #1031

2021-10-13 16:23 UTC, estherjsuh commented
@OmarIthawi that's a good idea. I separated out the beeling tracing to this #1031, I'll tag you there.

2021-11-09 11:58 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/api/tests/test_registration_api.py
> +            assert True, 'Should not call fake_send when no password'
`False` is intentional. Using `True` would effectively make the test case useless.

```suggestion
            assert False, 'Should not call fake_send when no password'
```

2021-11-09 11:58 UTC, OmarIthawi commented on openedx/core/djangoapps/user_authn/views/register.py
> +    skip_email = not params["send_activation_email"]
I think that's a good solution!

2021-11-09 11:59 UTC, OmarIthawi requested changes
Thanks @estherjsuh. I think you're getting to some good solution.

I just wanted to avoid disabling the test case.

2021-11-12 15:07 UTC, OmarIthawi commented
Thanks a lot for your help @estherjsuh! I'll close this PR in favor of:

 - https://github.com/appsembler/edx-platform/pull/1044

2021-11-12 15:07 UTC, closed without merging