PROTO II - create CompileSassView
appsembler/edx-platform pull request #1071
Opened 2022-02-02 17:26 UTC by estherjsuh

## PROTO II - create `CompileSassView`

2022-02-03 09:15 UTC, OmarIthawi requested changes
Thanks @estherjsuh. I've added few changes for the API view.

2022-02-03 09:15 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/sites/api.py
> +class CompileSassView(APIView):
```suggestion
class CompileSassView(APIView):
    """
    TODO: Document this API.
    """

    permission_classes = [ApiKeyHeaderPermission]

```

2022-02-03 09:15 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/sites/api.py
> +        configuration.compile_microsite_sass()
This is needed so `SiteConfiguration` model uses the service adapter.

```suggestion
        configuration.init_api_client_adapter(site)
        configuration.compile_microsite_sass()
```

2022-02-04 21:30 UTC, estherjsuh commented
@OmarIthawi I appreciate the review. I made the suggested changes and added testing - please give this PR another pass. Thanks!

2022-02-05 11:04 UTC, OmarIthawi approved these changes

2022-02-05 11:06 UTC, OmarIthawi commented
Thanks @estherjsuh! Looks great now, please deploy for testing on staging.

2022-02-07 09:46 UTC, thraxil approved these changes

2022-02-07 16:52 UTC, merged