Disable api-docs URL - RED-2861
appsembler/edx-platform pull request #1102
Opened 2022-03-16 10:43 UTC by shadinaif

## Change description

Disable api-docs URL because of a possible XSS security issue. Details in RED-2861

## Type of change
- [x] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

https://appsembler.atlassian.net/browse/RED-2861

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-03-16 10:54 UTC, OmarIthawi requested changes
this don't cause any conflict yet, but I think it will.

 - the idea is good, but please move it into `openedx/core/djangoapps/appsembler/settings/settings/production_common.py`
 - it also needs tests

2022-03-16 10:54 UTC, OmarIthawi commented on cms/envs/common.py
> +    # 'drf_yasg',
Please add this line into:

https://github.com/appsembler/edx-platform/blob/7b02818721fcfaa523c8a4bacfd84a780ecbc64c/openedx/core/djangoapps/appsembler/settings/settings/production_common.py#L13-L20


in the form of 
```py
settings.INSTALLED_APPS = [
    app for app in settings.INSTALLED_APPS
    if app != 'drf_yasg'
]
```

2022-03-18 12:46 UTC, shadinaif commented on cms/envs/common.py
> +    # 'drf_yasg',
Thank you @OmarIthawi . I know you'll hate hearing that I changed it completely. Tests didn't go well. The package is used by `edx-api-doc-tools` which is used in the code many times. Disabling `drf-yasg` safely will require many changes that leads to many code conflicts with upstream.

Please take a look now, this is the least impact on code I could come up with

2022-03-18 12:53 UTC, shadinaif commented on lms/tests.py
> +        self.assertEqual(404, response.status_code)
Note @OmarIthawi , this test is not actually included in our gitbub action tests

2022-03-18 21:58 UTC, OmarIthawi commented on lms/tests.py
> +        self.assertEqual(404, response.status_code)
@shadinaif please add the tests to `tox.ini` lms-1 or lms-2

2022-03-18 22:02 UTC, OmarIthawi commented on cms/urls.py
> +# urlpatterns += make_docs_urls(api_info)
a better pattern would be the following:
```suggestion
if settings.FEATURES.get('TAHOE_ENABLE_API_DOCS_URLS', False):
    urlpatterns += make_docs_urls(api_info)
```

It adds a sense of "feature" to the change we're doing and make it easier to search by the feature flag to identify different usage and affect of the feature.

2022-03-18 22:02 UTC, OmarIthawi commented on lms/urls.py
> +# urlpatterns += make_docs_urls(api_info)
same here

2022-03-18 22:02 UTC, OmarIthawi commented on lms/tests.py
> +        self.assertEqual(404, response.status_code)
groups the feature flag pieces and tests together


```suggestion
        self.assertFalse(settings.FEATURES.get('TAHOE_ENABLE_API_DOCS_URLS'))
        self.assertEqual(404, response.status_code)  # Tahoe: Changed from `200`
```

2022-03-18 22:02 UTC, OmarIthawi reviewed
thanks @shadinaif, that's a good fix.

please address the remaining changes.

2022-03-19 09:29 UTC, shadinaif commented on lms/tests.py
> +        self.assertEqual(404, response.status_code)
done

2022-03-19 09:29 UTC, shadinaif commented on cms/urls.py
> +# urlpatterns += make_docs_urls(api_info)
done

2022-03-19 10:28 UTC, OmarIthawi approved these changes

2022-03-19 10:30 UTC, merged