Use tahoe-sites.api - Patch 04b: Remove UserOrganizationMapping from openedx
appsembler/edx-platform pull request #1194
Opened 2022-07-19 12:51 UTC by shadinaif

## Change description

Use tahoe-sites.api - Patch 04b: Remove UserOrganizationMapping from openedx

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-07-26 16:11 UTC, OmarIthawi reviewed
@shadinaif please test the changes manually as noted inline.

2022-08-01 12:26 UTC, OmarIthawi commented
@shadinaif did you check the previous review? Please let me know if you've tested the steps on AMC and Dashboard locally?

2022-08-01 13:20 UTC, shadinaif commented on openedx/core/djangoapps/appsembler/sites/permissions.py
> +            is_organization_admin = is_active_admin_on_organization(
Thank you @OmarIthawi . I've removed the permission class `AMCAdminPermission` entirely and added a helper function to be used by `get_queryset`. Please review and let me know if I should revert this for any reason, or add tests to verify it ((already verified in devstack black-box testing))

2022-08-01 13:20 UTC, shadinaif commented on openedx/core/djangoapps/user_authn/views/register.py
> +                try:
same here

2022-08-01 15:05 UTC, OmarIthawi requested changes
@shadinaif thanks for your work here.

I suggest making a more gradual fix for the AMC permission issue.

This means this PR should not attempt to fix or improve the AMC permission in anyway, except for changing imports. Another PR should address that.

2022-08-02 07:02 UTC, OmarIthawi approved these changes
Thanks @shadinaif! Much better. I've added few minor changes. 

Please address them and this PR is good to go.

2022-08-02 07:02 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/sites/permissions.py
> +        is_organization_admin = UserOrganizationMapping.objects.filter(
The 1%, thanks!!

2022-08-02 07:02 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/sites/api.py
> +            except User.DoesNotExist:
`ObjectDoesNotExist` catches all models and in this case we have two models: User and Organization.

```suggestion
            except ObjectDoesNotExist:
```

2022-08-02 07:02 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/sites/permissions.py
>      """
```suggestion
    """
    
    # TODO: RED-2845 Remove this class when AMC is removed.
```

2022-08-02 07:41 UTC, shadinaif commented on openedx/core/djangoapps/appsembler/sites/permissions.py
>      """
Done

2022-08-02 07:41 UTC, shadinaif commented on openedx/core/djangoapps/appsembler/sites/api.py
> +            except User.DoesNotExist:
Done

2022-08-02 08:41 UTC, merged