Remove edx_uuid from the code
appsembler/edx-platform pull request #1213
Opened 2022-08-10 15:34 UTC by shadinaif

## Change description

Remove edx_uuid from the code

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

Related to: https://appsembler.atlassian.net/browse/RED-3274

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-08-11 09:12 UTC, OmarIthawi approved these changes
Thanks! Amazing!

2022-08-11 09:12 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/api/sites.py
> +        site = get_site_by_organization(organization=org_courses.first().organization)
Great for this pull request.

A note for the future: If we end up needing this a lot, I think it makes sense to add another API:

```
get_organization_for_course(course_id)
```

We can replace `get_site_for_course` into `get_site_by_organization(get_organization_for_course(course_id))`

2022-08-11 09:12 UTC, OmarIthawi commented on requirements/edx/appsembler.txt
> +-e git+https://github.com/appsembler/tahoe-sites.git@a14555e9e6c99097b2c97d8183fcb4218b4bbdb9#egg=tahoe-sites
```suggestion
tahoe-sites==1.2.1
```

2022-08-11 12:32 UTC, shadinaif commented on requirements/edx/appsembler.txt
> +-e git+https://github.com/appsembler/tahoe-sites.git@a14555e9e6c99097b2c97d8183fcb4218b4bbdb9#egg=tahoe-sites
sure, this is just temporary until the version is being released

2022-08-11 12:39 UTC, shadinaif commented on openedx/core/djangoapps/appsembler/api/sites.py
> +        site = get_site_by_organization(organization=org_courses.first().organization)
will do: https://github.com/appsembler/tahoe-sites/issues/56

2022-08-12 06:50 UTC, shadinaif commented on requirements/edx/appsembler.txt
> +-e git+https://github.com/appsembler/tahoe-sites.git@a14555e9e6c99097b2c97d8183fcb4218b4bbdb9#egg=tahoe-sites
Done

2022-08-12 06:59 UTC, OmarIthawi requested changes
Thanks @shadinaif!

I have many requested changes. The PR overall looks good, but we must do the following:


### Requested changes:

 - revert changes on `legacy_amc_helpers.py` to avoid breaking production AMC sites
 - undo `add_organization` changes
 - ask bryan to review the removal of TAHOE_ENABLE_MULTI_ORGS_PER_SITE

2022-08-12 06:59 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/sites/tests/test_utils.py
> -        'TAHOE_ENABLE_MULTI_ORGS_PER_SITE': True,
@shadinaif please check with @bryanlandia about this change. It may still be needed:

 - https://github.com/appsembler/edx-platform/pull/785

2022-08-12 06:59 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/sites/utils.py
> -        edx_uuid__in=[str(edx_uuid) for edx_uuid in active_tiers_uuids],
great!!

2022-08-12 06:59 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/sites/utils.py
> -                    if settings.FEATURES.get('TAHOE_ENABLE_MULTI_ORGS_PER_SITE', False):
ditto, this feature may be needed. please ask Bryan.

2022-08-12 06:59 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/tahoe_tiers/legacy_amc_helpers.py
> +        )
This will break all AMC sites in production.

Please revert this change. `legacy_amc_helpers` do _not_ need `tahoe_sites` integration.

2022-08-12 06:59 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/sites/utils.py
>              'short_name': organization_slug,
This line is harmless, even with the upstream edx-organization.

```suggestion
            'short_name': organization_slug,
            'edx_uuid': org_data.get('edx_uuid')  # TODO: RED-2845 Remove this line when AMC is migrated
```

2022-08-12 06:59 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/sites/serializers.py
> +        fields = ('id', 'name', 'short_name')
I think this change breaks AMC site creation. Let's find a way to keep it working.

Until we migrate all sites out of AMC, we will probably need this field to be there. Consider using a feature flag: zd_helpers etc/etc/etc.

```suggestion
        fields = ('id', 'name', 'short_name')
        if zd_helpers.use_org_models():
            fields += ('edx_uuid')
```

2022-08-22 16:34 UTC, OmarIthawi commented
@shadinaif regarding `TAHOE_ENABLE_MULTI_ORGS_PER_SITE` I think we should keep it removed. 

I've wrote a blog post which you can use for future reference:
 - [Tahoe standalone: Removal of TAHOE_ENABLE_MULTI_ORGS_PER_SITE feature](https://appsembler.atlassian.net/wiki/spaces/RT/blog/2022/08/22/2649260052/Tahoe+standalone+Removal+of+TAHOE+ENABLE+MULTI+ORGS+PER+SITE+feature)

2022-08-25 11:52 UTC, shadinaif commented on openedx/core/djangoapps/appsembler/tahoe_tiers/legacy_amc_helpers.py
> +        )
Done

2022-09-05 13:02 UTC, OmarIthawi approved these changes
Thanks @shadinaif!! One more _optional_ change. 

Looks good!

2022-09-08 06:49 UTC, shadinaif commented on openedx/core/djangoapps/appsembler/api/sites.py
> +        site = get_site_by_organization(organization=org_courses.first().organization)
Done

2022-09-08 06:50 UTC, merged