Fix Resume Course 404 issue
appsembler/edx-platform pull request #1217
Opened 2022-08-15 16:32 UTC by shadinaif

## Change description

Fix Resume Course 404 issue. Simulate https://github.com/openedx/edx-platform/pull/27046 without upgrading completion-package

## Type of change
- [x] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

Related to: https://appsembler.atlassian.net/browse/RED-3276

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-08-16 11:39 UTC, OmarIthawi requested changes
Thanks @shadinaif. Please change to the following:

 - Convert into a dedicated helper so the code isn't stray and we can tell it's our code: `appsembler.future_releases_hacks.helpers` module.
 - Import the helper in the `student/helpers.py` module
 - Add tests to the helper.
 - Add this PR to the list of tech-debt issues we have until we upgrade.

2022-08-17 14:32 UTC, shadinaif commented
Thank you @OmarIthawi , please take a look now

2022-08-18 04:32 UTC, OmarIthawi reviewed
Thanks @shadinaif, one more clean up please and it should be okay.

2022-08-18 04:32 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/future_releases_hacks/helpers.py
> +    raise UnavailableCompletionData(context_key)
```py
def url_to_block():
  try:
      block_data = get_course_blocks(user, block_key)
  except UsageKeyNotInBlockStructure:
      url_to_block = ''
  else:
      if block_key in block_data:
          url_to_block = reverse(
              'jump_to',
              kwargs={'course_id': enrollment.course_id, 'location': block_key}
          )
      else:
          url_to_block = ''
```

one more method please. This is going to help a lot during a release merge. 

it's very desirable to have as little change to upstream code as possible.

2022-08-18 04:32 UTC, OmarIthawi commented on common/djangoapps/student/helpers.py
> +
git noise

```suggestion
```

2022-08-18 04:32 UTC, OmarIthawi commented on common/djangoapps/student/helpers.py
> +from openedx.core.djangoapps.content.block_structure.exceptions import UsageKeyNotInBlockStructure
Keep our imports at the bottom of upstream imports. This reduces conflicts by a ton.

2022-08-18 05:46 UTC, shadinaif commented on common/djangoapps/student/helpers.py
> +
agree

2022-08-18 05:50 UTC, shadinaif commented
Thank you @OmarIthawi , and sorry that I didn't mention that after the first review: I removed my code and cherry-picked from upstream https://github.com/openedx/edx-platform/commit/f4974aebd52c08167f74f12769ef8f18e289627b . So, the new change request will create future conflicts, unlike the thing you're aiming for :)

2022-08-18 06:33 UTC, OmarIthawi approved these changes
> Thank you @OmarIthawi , and sorry that I didn't mention that after the first review: I removed my code and cherry-picked from upstream [openedx@f4974ae](https://github.com/openedx/edx-platform/commit/f4974aebd52c08167f74f12769ef8f18e289627b) . So, the new change request will create future conflicts, unlike the thing you're aiming for :)

Shocking 😆

2022-08-18 07:39 UTC, merged