explicitly set routing keys in settings
appsembler/edx-platform pull request #1226
Opened 2022-08-18 10:14 UTC by melvinsoft

## Change description

This is a follow up of https://github.com/appsembler/edx-configs/pull/1443 

The main grading task of the platform is routed in the `task` decorator, after merging the above PR I tested in staging and grading tasks are still getting into the default queue. Celery is really a mess, there are at least 4 or 5 different ways of routing tasks and they can be override... I'm not sure exactly why in our case sometimes grading tasks go to the default queue. 

Settings tasks and queues in settings in the Django Celery recommended way of doing this.

https://stackoverflow.com/questions/10707287/django-celery-routing-problems
https://stackoverflow.com/questions/29786019/why-do-celery-routes-have-both-a-queue-and-a-routing-key

## Type of change
- [x] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-08-18 12:45 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/settings/settings/production_common.py
> +    )
```diff
-tuple1 = (tuple1, something, something) # bad, nests tuple1
+tuple1 = tuple + (something, something,)  # good, appends to tuple1
```

2022-08-18 12:51 UTC, OmarIthawi requested changes
it seems like there's a syntax error as we talked

2022-08-19 10:11 UTC, melvinsoft commented on openedx/core/djangoapps/appsembler/settings/settings/production_common.py
> +    )
@OmarIthawi As I mentioned in person, I already went through this in figures and it worked this way: https://github.com/appsembler/figures/blob/main/figures/settings/lms_production.py#L104

2022-08-19 10:13 UTC, melvinsoft commented
@OmarIthawi Errors and tests fixed, please give it another look.

2022-08-19 10:35 UTC, thraxil approved these changes

2022-08-19 10:35 UTC, thraxil commented on openedx/core/djangoapps/appsembler/settings/settings/production_common.py
> +    )
So, assuming Open edX hasn't done anything sneaky (never a safe assumption), `CELERY_ROUTES` can either be just a dict that maps tasks to queues, or it can be a string indicating a router class to instantiate, or a two element tuple where the first element is a string indicating a router to instantiate and the second element is a dict with the additional mappings: https://docs.celeryq.dev/en/3.1/configuration.html#celery-routes

So @melvinsoft's syntax here appears to be right, although it's definitely confusing. Especially since the `lms.envs.production` sets it to a string: https://github.com/appsembler/edx-platform/blob/main/lms/envs/production.py#L157 and it's not obvious (to me, at least) what order things are executed and how the plugin settings all interact.

2022-08-19 10:35 UTC, thraxil commented on openedx/core/djangoapps/appsembler/settings/tests/test_settings.py
> +    settings.CELERY_ROUTES = ()
It probably isn't being used in the settings (or is overridden somewhere else), but I think an empty tuple is one of the only values that `CELERY_ROUTES` probably can't be. I think `{}` is probably what we want, but I doubt it matters here.

2022-08-19 11:03 UTC, melvinsoft commented on openedx/core/djangoapps/appsembler/settings/settings/production_common.py
> +    )
@thraxil Thanks for the feedback, Open edX has done something sneaky here, or at least not super clear. The first value (and the only by default) it points to a router class which a base class `lms.celery.Router` and here is [the file](https://github.com/appsembler/edx-platform/blob/main/lms/celery.py).

Celery allows you to put on the same settings value `CELERY_ROUTES` strings pointing to classes, JSON dicts with routing syntax or a Router object itself, which is what we are doing for figures. So I think this change should work, anyway, I want to test on Staging and revert if it doesn't.

2022-08-19 12:03 UTC, OmarIthawi requested changes
one more thing, thanks @melvinsoft

2022-08-19 12:03 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/settings/settings/production_common.py
> +                'routing_key': settings.ENV_TOKENS.get('RECALCULATE_GRADES_ROUTING_KEY', settings.DEFAULT_PRIORITY_QUEUE)
It looks like we have a typo here, `RECALCULATE_GRADES_ROUTING_KEY` is being used twice on both `queue` and `routing_key`. Isn't that a typo?

2022-08-19 12:29 UTC, melvinsoft commented on openedx/core/djangoapps/appsembler/settings/settings/production_common.py
> +                'routing_key': settings.ENV_TOKENS.get('RECALCULATE_GRADES_ROUTING_KEY', settings.DEFAULT_PRIORITY_QUEUE)
No, Celery is a mess, in this case, for consistency, `queue` and `routing_key` have the same value.

https://stackoverflow.com/questions/29786019/why-do-celery-routes-have-both-a-queue-and-a-routing-key

2022-08-19 12:34 UTC, OmarIthawi approved these changes
> No, Celery is a mess,

That sums it up. Thanks @melvinsoft!!

2022-08-19 12:35 UTC, merged