get custom domains from own models instead of AMC db
appsembler/edx-platform pull request #1239
Opened 2022-09-05 14:25 UTC by melvinsoft

## Change description

Soon we will deprecate AMC and the postgres database won't exist anymore, I realized setting up a custom domains, all the info this commands gets from the AMC database is the same as the alternative domains 

## Type of change
- [x] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-09-14 08:30 UTC, OmarIthawi requested changes
@melvinsoft thanks a lot for removing AMC db call from the command.

I think we need a new field `AlternativeDomain.cert_pending` to distinguish between pending certs and ready certs.

I've checked the code and I'm not sure if it'll work well or not given that we don't store the `cert_pending` state anywhere and we may be moving from one unreliable to another unreliable workflow.

Please also add tests for this code.

2022-09-15 12:15 UTC, melvinsoft commented
@OmarIthawi Thank you so much for the review. 

Here is the issue, as you know we have been talking about fixing custom domains and move to something like Traefik, so adding a new field here, also means we need to change logic in Tahoe cert agent and our Ansible playbooks, I don't even know how to start implementing that logic. I understand the tests, but this command is only being used by Tahoe cert agent, the piece we want to deprecate, so I don't think it worth it.
 
In the other hand, I already consumed all my coding buffers for this sprint and this tasks, so I cannot invest more myself in this, what I achieved is something it can be executed with a runbook or a script, and allow an engineer to set up a new custom domains in about 1 hr, with our current conflicting priorities and capacity, we shouldn't fix this further at this stage.

2022-09-15 12:44 UTC, OmarIthawi reviewed
Thanks again Maxi Sorry for not making my original review clearer. 

**Required changes:** Please add tests now that AMC database isn't accessed.

**Suggested change:** ~Add `cert_pending` field~ we agreed that we'll not perform this change. 

**Suggested change:** Only return active sites.

2022-09-15 12:44 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/sites/management/commands/custom_domains_list.py
> +        altertive_domains = AlternativeDomain.objects.values_list('site__domain', flat=True)
Should we filter by `get_active_sites`? Can we?


```suggestion
        altertive_domains = AlternativeDomain.objects.filter(
            site__in=get_active_sites(),
        ).values_list('site__domain', flat=True)
```

As long as the Ansible playbook uses `www-data` this change should be okay.

```yaml
- name: List custom domains
  become: www-data
  shell: ./manage lms custom_domains_list 
```

2022-09-15 14:34 UTC, thraxil commented
I added a simple test to show how easy it is. It should be expanded with some more test cases to, eg, verify that Omar's recommendation of only including active sites works correctly.

2022-09-15 16:09 UTC, OmarIthawi approved these changes
Thanks @melvinsoft and @thraxil. This pull request looks great already after adding the tests.

Let's get it merged and I may add the `get_active_sites` later.

2026-05-22 17:17 UTC, closed without merging