Fix get_or_create_enrollment to save the correct key
appsembler/edx-platform pull request #1291
Opened 2022-10-05 12:01 UTC by shadinaif

## Change description

Fix `get_or_create_enrollment` to save the correct key

The last assertion in the added test will fail without the fix
```python
self.assertEqual(enrollment.course_id, course.id)
```

**Note:** the test is a little bit complicated because SQLite does not support case-insensitive search with unicode. See comments in the test

## Type of change
- [x] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

Related issue: https://appsembler.atlassian.net/browse/RED-3435

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-10-05 12:14 UTC, OmarIthawi approved these changes
Thanks a lot Shadi!!

Here's a little Open edX little known code style:

 - `course_id` is usually used for the string course ID type
 - `course_key` is usually used for the object (aka CourseKey) course ID type

To avoid all of this confusion, it's better to use override `course_key` and put a note to avoid misleading engineers who read this.

2022-10-05 12:14 UTC, OmarIthawi commented on common/djangoapps/student/models.py
> +        course_id = CourseOverview.get_from_id(course_key).id
```suggestion
        # Accept the incorrect course key case, but convert to the correct letter case of 
        # the Course ID to avoid running into MongoDB vs. MySQL case sensitivity issues.
        course_key = CourseOverview.get_from_id(course_key).id
```

2022-10-05 12:14 UTC, OmarIthawi commented on common/djangoapps/student/models.py
> +            course_id=course_id,
```suggestion
            course_id=course_key,
```

2022-10-05 12:14 UTC, OmarIthawi commented on common/djangoapps/student/models.py
> +            course_id=course_id,
```suggestion
            course_id=course_key,
```

2022-10-05 12:53 UTC, shadinaif commented on common/djangoapps/student/models.py
> +        course_id = CourseOverview.get_from_id(course_key).id
done

2022-10-05 12:53 UTC, shadinaif commented on common/djangoapps/student/models.py
> +            course_id=course_id,
done

2022-10-07 07:02 UTC, OmarIthawi requested changes
@shadinaif let's hold on a bit for this. Maybe the data fix will be all what we need.

With the try/catch we may need to understand enrollment better before putting this fix in.

The recommended approach now is to fix this upstream and then cherry-pick it.

2022-10-07 10:58 UTC, shadinaif commented
Agree @OmarIthawi 👍🏼

2022-10-28 14:43 UTC, OmarIthawi requested changes
Is it possible to move the logic into these lines?

https://github.com/appsembler/edx-platform/blob/6bd1275fe447590e7ab5a59e275a426a754d3b40/openedx/core/djangoapps/appsembler/api/v1/views.py#L348-L361


I recommend this to avoid changing the core for something that's only useful for our Enrollment API.

2022-11-02 13:10 UTC, shadinaif commented
Closing it in favour of https://github.com/appsembler/edx-platform/pull/1303

2022-11-02 13:10 UTC, closed without merging