Add get_redirect_to_lms_login_url helper
appsembler/edx-platform pull request #1301
Opened 2022-10-27 07:08 UTC by shadinaif

## Change description

Add `get_redirect_to_lms_login_url` to be used by our theme to redirect to LMS login if needed

**Example scenario before this change:**
* Studio is not logged in yet
* An author clicks (View Unit in Studio) in LMS <LMS logged in for sure>
* Redirects to Studio Login page. The user must follow instructions and open studio though LMS

**Same scenario after this change:**
* Studio is not logged in yet
* An author clicks (View Unit in Studio) in LMS <LMS logged in for sure>
* Redirects to Studio Login page
* Studio fetches the `course_id` from `next` argument in the URL
* Now studio knows the related site: redirects to `https://the_site/studio/?next=***`
* Auto magic-link performed, then a redirect to the originally requested page is performed

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

Related to: https://appsembler.atlassian.net/browse/RED-3242

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-10-27 08:29 UTC, OmarIthawi requested changes
Thanks Shadi!!

**Required change:** I think the code is designed to work with the _incorrect_ course IDs.

Course IDs are always `course-v1:org+course+run` e.g. `course-v1:redis+cache+2022_Sprint`. I think both of the code and test cases are incorrect.

**Suggested change:** Try to get the organization ID instead of the course ID. If you think this is a good idea.

2022-10-27 08:29 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/tahoe_idp/helpers.py
> +        return re.sub(r'^.+/course-v1:(.+)', r'course-v1:\1', url)
> Some people, when confronted with a problem, think "I know, I'll use regular expressions." Now they have two problems. -- [CodingHorror](https://blog.codinghorror.com/regular-expressions-now-you-have-two-problems/)


Snarkiness aside `course-v1:(.+)` is the wrong pattern to match against. It needs to be a more explicit pattern: `course-v1:([^+]+)` so it doesn't eagerly catch other plusses. Or better, it should be the exact edX patterns for course keys:

 - https://github.com/openedx/opaque-keys/blob/master/opaque_keys/edx/locator.py

2022-10-27 08:29 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/tahoe_idp/tests/test_tahoe_idp_helpers.py
> +    ('https://example.com/some_path/course-v1:ORG+org_2022', 'course-v1:ORG+org_2022'),
Course IDs are always `course-v1:org+course+run` e.g. `course-v1:redis+cache+2022_Sprint`. I think both of the code and test cases are incorrect.

2022-10-27 08:29 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/tahoe_idp/helpers.py
> +def extract_course_id_from_url(url):
That would be an easier task to do.

```suggestion
def extract_org_short_name_from_url(url):
```

2022-10-27 08:29 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/tahoe_idp/helpers.py
> +        organization = get_organization_by_course(course_id)
```suggestion
        organization = Organization.objects.get(short_name=org_short_name)
```

2022-10-28 14:22 UTC, shadinaif commented on openedx/core/djangoapps/appsembler/tahoe_idp/helpers.py
> +        return re.sub(r'^.+/course-v1:(.+)', r'course-v1:\1', url)
Done, thank you!

2022-10-28 14:28 UTC, shadinaif commented
I've refactored the code @OmarIthawi , please take a look now 🌷

2022-10-28 14:33 UTC, OmarIthawi approved these changes
Thanks @shadinaif for going through this RegExp mess! I think it's much better now.

Tests also looks really good!

2022-10-28 15:06 UTC, merged