chore: add valid_url_pattern for logout
appsembler/edx-platform pull request #1340
Opened 2023-04-14 22:34 UTC by amirtds

Making sure the redirect URL has valid protocol

2023-04-14 23:30 UTC, bryanlandia reviewed
question for you, otherwise looks good.

2023-04-14 23:30 UTC, bryanlandia commented on openedx/core/djangoapps/user_authn/views/logout.py
> +            if parsed_url.scheme not in ('http', 'https') and not valid_url_pattern.match(target_url) and not parsed_url.path.startswith('/'):
@amirtds Don't we need to support `?redirect_url=doesnt_start_with_a_slash' ?  It might not be a real-world use case.  What do you think?

2023-04-14 23:51 UTC, bryanlandia requested changes
Looks like     def test_logout_redirect_failure_with_xss_vulnerability(self, redirect_url, host): fails now

2023-04-15 01:27 UTC, amirtds commented on openedx/core/djangoapps/user_authn/views/logout.py
> +            if parsed_url.scheme not in ('http', 'https') and not valid_url_pattern.match(target_url) and not parsed_url.path.startswith('/'):
@bryanlandia The redirect URL should be external (starting with HTTPS or HTTP) or be relative path (/courses, index page etc) if it doesn't pass this 2 cases we set it as `/`

2023-04-18 02:24 UTC, bryanlandia approved these changes
thanks Amir.  Tests pass now.

2023-04-18 02:25 UTC, merged