Add import command
appsembler/edx-platform pull request #568
Opened 2020-04-17 18:10 UTC by ahmedaljazzar

This is the LMS version of export's data import that was introduced in #565. 

Suggested test cases:

1. Importing into a live site:
    1. Create a temp site using `python manage.py lms create_devstack_site orange` on LMS.
    1. Do some modifications on the Admin Panel, related to your site. (Configurations is an example)
    1. Export the site using `python manage.py lms export_site orange.localhost:18000`
    1. Delete the site using `python manage.py lms remove_site orange.localhost:18000`. You can also try to remove as many related objects as you want from the DB like Orange's site users and stuff.
    1. Make sure that the site is not functional.
    1. Run `python manage.py lms import_site /export/file/path.json` to import all of the objects.
    1. The site should return to the same state it was exported on. (Users, objects, links, permissions, ...) and should link automatically with AMC.
1. Importing into a new site: (Suitable for Tahoe UK)
    1. Create a temp site using `python manage.py lms create_devstack_site orange` on LMS.
    1. Do some modifications on the LMS, AMC part from Django Admin and from the UI. Try to include as many use cases as you can.
    1. Export the site using `python manage.py lms export_site orange.localhost:18000`
    1. Delete or create a new clean devstack.
    1. Run `python manage.py lms import_site /export/file/path.json` to import all of the objects.
    1. The site should return to the same state it was exported on. (Users, objects, links, permissions, ...).

AMC PR: [amc#305](https://github.com/appsembler/amc/pull/305)

2020-04-23 13:07 UTC, OmarIthawi commented
@ahmedaljazzar thanks again for making this. I need to go over this PR to see how models with implicit foreign key are treated e.g. there's a lot of models with `course_id` as a regular CharField without explicit ForeignKey relationship. There's is a good chance that's not an issue, but it's worth double checking.

Let's put it on hold until we merge the AMC pr: https://github.com/appsembler/edx-platform/pull/565.

2020-11-17 07:44 UTC, OmarIthawi requested changes
@ahmedaljazzar this PR has been open for a while. I'd like to get it moved to either of

 - Mark the command with clear `unstable_site_import` prefix and merge it
 - Close this PR and add a Jira task for yourself for follow up (if there isn't one already)

2020-11-17 07:44 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/sites/tests/test_commands.py
> +        self.command = ImportSiteCommand()
```suggestion
        self.command = UnstableImportSiteCommand()
```

2020-12-15 02:54 UTC, ahmedaljazzar commented
Closing this for now, will continue on it later with Juniper release.

2020-12-15 02:54 UTC, closed without merging