Make individual due dates microsite aware
appsembler/edx-platform pull request #706
Opened 2020-10-27 22:05 UTC by melvinsoft

The Extensions tab in the instructor dashboard has serious performance issues, and some sites doesn't need it, so this PR allow us to turn off per site. A follow up step is to make is configurable in AMC.

2020-10-28 08:07 UTC, OmarIthawi requested changes
@melvinsoft I've added some needed comments. Please also fix any `pep8` issues: https://travis-ci.org/github/appsembler/edx-platform/jobs/739443520

2020-10-28 08:07 UTC, OmarIthawi commented on lms/djangoapps/instructor/views/instructor_dashboard.py
> +    if configuration_helpers.get_value('INDIVIDUAL_DUE_DATES', True) and access['instructor']:
The default site-wide config should be kept.

```suggestion
    if configuration_helpers.get_value(
        'INDIVIDUAL_DUE_DATES',
        settings.FEATURES.get('INDIVIDUAL_DUE_DATES')
    ) and access['instructor']:
```

2020-10-28 08:07 UTC, OmarIthawi commented on lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
> +    @override_settings(INDIVIDUAL_DUE_DATES=True) # default value in congif
Overriding the global feature isn't required. It's not a `settings` flag.

```suggestion
```

It's a `settings.FEATURES` flag so it should be except that we don't need it.

```
@patch.dict(settings.FEATURES, {'INDIVIDUAL_DUE_DATES': True})
```

2020-10-28 08:07 UTC, OmarIthawi commented on lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
> +    @override_settings(INDIVIDUAL_DUE_DATES=False) # default value in congif
```suggestion
```

2020-10-28 08:07 UTC, OmarIthawi commented on lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
> +                'course_id': unicode(self.course_info.id)
Python 3

```suggestion
                'course_id': str(self.course_info.id)
```

2020-10-28 08:07 UTC, OmarIthawi commented on lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
> +                'course_id': unicode(self.course_info.id)
Python 3

```suggestion
                'course_id': str(self.course_info.id)
```

2020-10-28 10:01 UTC, johnbaldwin commented
I don't have anything additional to add at this time. Thanks for adding these tests, Maxi!

2020-10-28 13:11 UTC, OmarIthawi commented on lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
> +        'INDIVIDUAL_DUE_DATES': True, # site configuration override
```suggestion
        'INDIVIDUAL_DUE_DATES': True,  # site configuration override
```

2020-10-28 13:11 UTC, OmarIthawi commented on lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
> +        'INDIVIDUAL_DUE_DATES': False, # site configuration override
```suggestion
        'INDIVIDUAL_DUE_DATES': False,  # site configuration override
```

2020-10-28 13:12 UTC, OmarIthawi approved these changes
LGTM now. Please wait for the tests to pass before merging this PR.

2020-10-29 13:24 UTC, melvinsoft commented on lms/djangoapps/instructor/views/instructor_dashboard.py
> +    if configuration_helpers.get_value('INDIVIDUAL_DUE_DATES', True) and access['instructor']:
Fixed. Thanks @OmarIthawi

2020-10-29 13:25 UTC, melvinsoft commented on lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
> +    @override_settings(INDIVIDUAL_DUE_DATES=False) # default value in congif
Fixed.

2020-10-29 13:25 UTC, melvinsoft commented on lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
> +                'course_id': unicode(self.course_info.id)
Fixed.

2020-10-29 13:25 UTC, melvinsoft commented on lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
> +        'INDIVIDUAL_DUE_DATES': True, # site configuration override
Fixed.

2020-10-29 13:25 UTC, melvinsoft commented on lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
> +        'INDIVIDUAL_DUE_DATES': False, # site configuration override
Fixed.

2020-10-29 13:25 UTC, melvinsoft commented on lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
> +                'course_id': unicode(self.course_info.id)
Fixed.

2020-10-29 13:25 UTC, melvinsoft commented on lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
> +    @override_settings(INDIVIDUAL_DUE_DATES=True) # default value in congif
Fixed.

2020-10-29 16:32 UTC, melvinsoft commented
@OmarIthawi @johnbaldwin Thank you both for your reviews, we're all set here, I'm going to wait for the tests after the rebase, and we're ready to merge.

2020-10-30 08:00 UTC, OmarIthawi commented
Thanks @melvinsoft, it should be good to get merged.

2020-10-30 12:54 UTC, merged