Return exception if cannot get the site config in event in segment top level processor
appsembler/edx-platform pull request #784
Opened 2020-12-11 20:41 UTC by melvinsoft

Figures is hitting a lot of exceptions generated by this processor while running the pipeline:
```
2020-12-11 09:11:38,675 ERROR 22421 [eventtracking.backends.routing] routing.py:114 - Failed to execute processor: <openedx.core.djangoapps.appsembler.eventtracking.segment.SegmentTopLevelPropertiesProcessor object at 0x7efcba5b50d0>
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/eventtracking/backends/routing.py", line 107, in process_event
    modified_event = processor(processed_event)
  File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/appsembler/eventtracking/segment.py", line 70, in __call__
    siteconfig = utils.get_site_config_for_event(event['data'])
  File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/appsembler/eventtracking/utils.py", line 34, in get_site_config_for_event
    site = utils.get_site_by_organization(org)
UnboundLocalError: local variable 'org' referenced before assignment
```
When there is not a site, the event should go main Appsembler segment destination only.

2020-12-11 21:37 UTC, bryanlandia requested changes
Thanks @melvinsoft I made a few suggestions

2020-12-11 21:37 UTC, bryanlandia commented on openedx/core/djangoapps/appsembler/eventtracking/utils.py
> +                    "There isn't and org or course_id attribute set in the "
```suggestion
                    "There isn't an org or course_id attribute set in the "
```

2020-12-11 21:37 UTC, bryanlandia commented on openedx/core/djangoapps/appsembler/eventtracking/utils.py
>          except (
```suggestion
        except (
            AssertionError,
            IndexError,
```

2020-12-11 21:37 UTC, bryanlandia commented on openedx/core/djangoapps/appsembler/eventtracking/utils.py
>          except (
I think we need to handle `utils.get_site_by_organization(org)` not finding a Site at all (`objects.all()[0]` gives IndexError or the `assert` in that function fails )

2020-12-14 12:18 UTC, melvinsoft commented on openedx/core/djangoapps/appsembler/eventtracking/utils.py
>          except (
@bryanlandia I don't think do, the function already handles two potential problems:
- Not finding not finding a Site at all. 
- Finding and org with more than 1 site.

https://github.com/appsembler/edx-platform/blob/08ed475b9bf7b01fece2b13e6d910c0d886edbf8/openedx/core/djangoapps/appsembler/sites/utils.py#L44-L50

2020-12-14 12:19 UTC, melvinsoft commented
@bryanlandia Thanks for the review and the comments, I replied on them.

2020-12-14 12:23 UTC, melvinsoft commented on openedx/core/djangoapps/appsembler/eventtracking/utils.py
>          except (
I think the problem we're solving here is inside this function, the problem was the `elif`, when the function receives an event without `org` or `course_id` it just don't enter in any part of the if statement, where org variable is defined, and it tries to return it anyway. This PRs adds a `else` so we make sure it will always return a controlled exception at least.

2020-12-14 22:05 UTC, bryanlandia commented on openedx/core/djangoapps/appsembler/eventtracking/utils.py
>          except (
Sure, I see what you are doing with adding the `else` and that is needed.  

I just meant we may also want to handle these other possible sources of unhandled exceptions within `get_site_by_organization`.  If org is None, then we would get an AttributeError not an AssertionError, and that's already handled in our try/except wrapper.  I'm just wondering, in case we may have an event where the course org is passed in the event but the org is no longer associated with one and only one Site, we could get other unhandled Exceptions which would cause problems for Figures.  Would this happen? I don't know, probably not so feel free to skip my suggestion if you want. 

Just to clarify, this is what I was looking at.  Let's say we kind of mock out `get_site_by_organization` as

```python
def get_site_by_organization(org):
    raise AssertionError
```

then currently our `except` block in `get_site_config_for_event` will not catch it and will raise the exception instead of dropping the event.  Same thing if the org has no related Site so `org.sites.all()[0]` raises an `IndexError`.

2020-12-14 22:20 UTC, bryanlandia commented on openedx/core/djangoapps/appsembler/eventtracking/utils.py
>          except (
I'll approve if you want to go ahead without this other change

2020-12-14 22:20 UTC, bryanlandia commented
approving

2020-12-14 22:21 UTC, bryanlandia approved these changes

2020-12-15 13:41 UTC, melvinsoft commented on openedx/core/djangoapps/appsembler/eventtracking/utils.py
>          except (
@bryanlandia I get your point, I added the suggestion to the code. Thanks!

2020-12-15 15:34 UTC, johnbaldwin commented on openedx/core/djangoapps/appsembler/eventtracking/utils.py
> +                raise exceptions.EventProcessingError(
@melvinsoft Why do we want to raise an exception here? Won't it just replace one exception message in the logs with another and not reduce the noise in the logs?

2020-12-15 20:08 UTC, bryanlandia commented on openedx/core/djangoapps/appsembler/eventtracking/utils.py
> +                raise exceptions.EventProcessingError(
@johnbaldwin Your question makes sense,  but there is a try/except that wraps the call to this function which just drops the event when an `EventProcessingError` occurs, so it shouldn't block Figures.

2020-12-15 21:58 UTC, melvinsoft commented on openedx/core/djangoapps/appsembler/eventtracking/utils.py
> +                raise exceptions.EventProcessingError(
@johnbaldwin Yes, the question makes sense, but this should stop the noise in the logs, since in the two places when it's been called, the exception is being handled. It actually makes sense to throw an exception if we cannot tie the event to an org.

The event will be sent to main Appsembler segment account, but not to the specific customer.

https://github.com/appsembler/edx-platform/blob/37fcb8eb805beb151d455057b77aee9c70daac63/openedx/core/djangoapps/appsembler/eventtracking/segment.py#L69-L77

and here

https://github.com/appsembler/edx-platform/blob/appsembler/tahoe/master/common/djangoapps/track/shim.py#L144-L161

2020-12-15 21:59 UTC, merged