Allow auto-generation of certs (e.g., on passing grade) for Honor mode
appsembler/edx-platform pull request #794
Opened 2020-12-23 07:02 UTC by bryanlandia

Even as of Koa, auto-generation of certs is not allowed for Audit or Honor.   It is allowed for Verified, Credit, Professional, and No ID Professional.  https://github.com/edx/edx-platform/blob/151bd136667d27bf85256e382ed5b5ea0144e00f/lms/djangoapps/certificates/signals.py#L145 

None of the allowed modes work for Tahoe because:

* A payment workflow is enforced for enrollment with mode Verified, Professional, and No ID Professional
* Credit is meant to a purchased add-on mode after course completion and expects a credit provider id

So, we should just allow auto-certs for Honor.  This PR does that.

2020-12-23 07:06 UTC, bryanlandia commented
Also note:  auto-cert generation isn't turned  on for Tahoe SaaS anyhow (probably because it requires PersistentGrades), but we are using it for DHIS2 on Tahoe standalone.  Some info on enabling it is here https://appsembler.atlassian.net/wiki/spaces/BLA/pages/62652425/DHIS2+Hawthorn+upgrade+plan#1b.-Manual-configuration

2020-12-23 08:36 UTC, OmarIthawi requested changes
Thanks @bryanlandia! This is helpful!

Please add a feature flag for it so it's maintainable and we can quickly find the related code for it.

We'll also need to add something like this in the Tahoe settings overrides `openedx/core/djangoapps/appsembler/settings/settings/common.py`:

```py
# Appsembler allows generating honor certs
settings.FEATURES['TAHOE_AUTO_GENERATE_HONOR_CERTS'] = True
```

2020-12-23 08:36 UTC, OmarIthawi commented on lms/djangoapps/certificates/signals.py
>      ]
```suggestion
    if settings.FEATURES['TAHOE_AUTO_GENERATE_HONOR_CERTS']:
        # Appsembler change: allow for Honor mode
        allowed_enrollment_modes_list += [
            CourseMode.HONOR
        ]
```

2020-12-23 08:36 UTC, OmarIthawi commented on lms/djangoapps/certificates/tests/test_signals.py
> +        ('honor', True),  # Appsembler allows for honor
```suggestion
        ('honor', True),  # TAHOE_AUTO_GENERATE_HONOR_CERTS feature: allows for honor
```

2020-12-23 08:36 UTC, OmarIthawi commented on lms/djangoapps/certificates/tests/test_signals.py
>      @ddt.unpack
```suggestion
    @ddt.unpack
    @patch.dict(settings.FEATURES, {'TAHOE_AUTO_GENERATE_HONOR_CERTS': True})
```

2020-12-23 19:06 UTC, bryanlandia commented
Updated with your suggestions @OmarIthawi and related fixes, then squashed.

2020-12-24 17:44 UTC, OmarIthawi approved these changes

2020-12-24 17:44 UTC, OmarIthawi commented
Looks great!

2020-12-28 23:25 UTC, merged