Juniper upgrade - added skipIf to failing lms.certificates tests
appsembler/edx-platform pull request #827
Opened 2021-02-16 19:58 UTC by johnbaldwin

Added `skipIf` to failing tests in `lms.certificates`. I investigated a bit, but it is quite the time sink. We'll need to address these.

2021-02-17 08:31 UTC, OmarIthawi requested changes
Thanks @johnbaldwin for working on those tests we need to enable as much tests as can afford. I have two notes:

1) I see that those tests are not included in the `tox.ini` whitelist. Please include them, otherwise they won't be runing.

2) `TAHOE_ALWAYS_SKIP_TEST` should be used only when we mostly certain that we don't want to look at the test again. If we're in doubt (like in this case) we should use the other flag `TAHOE_TEMP_MONKEYPATCHING_JUNIPER_TESTS` which means that we're just skipping it but generally should take another look.

2021-02-17 08:31 UTC, OmarIthawi commented on lms/djangoapps/certificates/tests/test_api.py
> +                     'Skip test due to failing first condition. See test docstring')
```suggestion
    @unittest.skipIf(settings.TAHOE_TEMP_MONKEYPATCHING_JUNIPER_TESTS,
                     'Failing tests for unclear reasons, disabling temporarily.')
```

2021-02-17 08:31 UTC, OmarIthawi commented on lms/djangoapps/certificates/tests/test_api.py
> +        self.assertEqual(response_data['is_downloadable'], cert_downloadable_status)
Please revert those changes so we avoid merge conflicts in the future.

2021-02-17 08:31 UTC, OmarIthawi commented on lms/djangoapps/certificates/tests/test_webview_views.py
> +    @unittest.skipIf(settings.TAHOE_ALWAYS_SKIP_TEST, 'Test fails. See test method docstring')
```suggestion
    @unittest.skipIf(settings.TAHOE_TEMP_MONKEYPATCHING_JUNIPER_TESTS, 
                              'Failing test. Could not fix it.')
```

2021-02-17 08:31 UTC, OmarIthawi commented on lms/djangoapps/certificates/tests/test_webview_views.py
> +
Please revert this change, it could create merge conflict and the failure should be reproducible in the future.

2021-02-17 08:31 UTC, OmarIthawi commented on lms/djangoapps/certificates/tests/test_api.py
> +        Failing test condition:
```suggestion
        ## Tahoe: Failing test condition
```

2021-02-17 08:31 UTC, OmarIthawi commented on lms/djangoapps/certificates/tests/test_webview_views.py
> +    @unittest.skipIf(settings.TAHOE_ALWAYS_SKIP_TEST, 'Test fails. See test method docstring')
```suggestion
    @unittest.skipIf(settings.TAHOE_TEMP_MONKEYPATCHING_JUNIPER_TESTS, 'Failing test. Could not fix it.')
```

2021-02-17 08:31 UTC, OmarIthawi commented on lms/djangoapps/certificates/tests/test_webview_views.py
> +        """
Ditto. Please remove.

2021-02-17 08:31 UTC, OmarIthawi commented on lms/djangoapps/certificates/tests/test_webview_views.py
> +    @unittest.skipIf(settings.TAHOE_ALWAYS_SKIP_TEST, 'Test fails. See test method docstring')
```suggestion
    @unittest.skipIf(settings.TAHOE_TEMP_MONKEYPATCHING_JUNIPER_TESTS, 'Test fails. Could not fix.')
```

2021-02-17 08:31 UTC, OmarIthawi commented on lms/djangoapps/certificates/tests/test_webview_views.py
> +        """
```suggestion
```

2021-02-17 12:12 UTC, johnbaldwin commented
@OmarIthawi please review again

2021-02-17 13:21 UTC, OmarIthawi reviewed
Thanks @johnbaldwin! This is much better.

Would you mind make the flag and their comments more consistent? It's not really wrong, just a bit confusing to have.

2021-02-17 13:21 UTC, OmarIthawi commented on lms/djangoapps/certificates/tests/test_webview_views.py
> +    @unittest.skipIf(settings.TAHOE_ALWAYS_SKIP_TEST, 'Failing test. Needs investigation to fix.')
The flag and the comment are not consistent.

If we aim to fix it even in a year from now I'd recommend `TAHOE_TEMP_MONKEYPATCHING_JUNIPER_TESTS`.

If we're not aiming to fix it since it's a date failure or something we don't care about, then we probably want to change the comment to something like `Failing test. Spent few hours on it. Skipping for the meantime.` so it attracts less energy from the engineer looking at it.

2021-02-17 13:21 UTC, OmarIthawi commented on lms/djangoapps/certificates/tests/test_webview_views.py
> +    @unittest.skipIf(settings.TAHOE_ALWAYS_SKIP_TEST, 'Test fails. Needs investigation to fix.')
Ditto.

2021-02-17 13:21 UTC, OmarIthawi commented on lms/djangoapps/certificates/tests/test_webview_views.py
> +    @unittest.skipIf(settings.TAHOE_ALWAYS_SKIP_TEST, 'Test fails. Needs investigation to fix.')
Ditto.

2021-02-17 13:21 UTC, OmarIthawi commented on tox.ini
> +        lms/djangoapps/certificates/tests/
Please move it to either `lms-1` or `lms-2`. `testenv:common` is not a good place to run those tests.

2021-02-17 13:24 UTC, OmarIthawi commented on tox.ini
> +        lms/djangoapps/appsembler_tiers/tests.py \
this exists in `lms` tox env already

2021-02-17 20:06 UTC, johnbaldwin commented
@OmarIthawi Did the latest update adequately address your concerns? Anything else?

2021-02-18 09:25 UTC, OmarIthawi approved these changes
> @OmarIthawi Did the latest update adequately address your concerns? Anything else?

It does 😁. It looks great actually. Thank you for going to the extra mile and addressing all the requested changes.

2021-02-18 10:58 UTC, merged