get_lms_link_for_course_key return base URL if AssertionError w/ Org
appsembler/edx-platform pull request #836
Opened 2021-02-24 21:10 UTC by bryanlandia

if an Organization is related to 0 or more than 1 Sites, then
get_site_for_course will raise an AssertionError.  We don't want that
to break views, esp. like Studio courses list

2021-02-24 21:27 UTC, bryanlandia commented
Currently, we are getting ann error at https://studio.staging-tahoe.appsembler.com/home/
because `appsembler-1` Org has no related Sites, which throws an AssertionError killing the whole view.  I checked and on prod there are no Orgs without a Site, but let's not risk a problem like that on prod.

2021-03-01 08:25 UTC, OmarIthawi requested changes
Thanks @bryanlandia. I've added a suggestion which refactors this PR.

2021-03-01 08:25 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/sites/utils.py
> +        course_site = get_site_for_course(course_key)
Assertion errors are somewhat rude and not meant to be caught. instead they're more of a "panic, I have no idea what to do here, throw a 500 error".

Instead of this change please make ensure that the `get_site_for_course` does _not_ throw such exception.

2021-03-20 09:47 UTC, OmarIthawi commented
@bryanlandia what's the status of this PR?

2021-09-02 15:23 UTC, OmarIthawi commented
@bryanlandia do you still want to work on this Pull Request?

2021-09-03 00:07 UTC, bryanlandia commented
Thanks for bugging me about it! I probably can't until Sprint 95 but late September it'll be back in focus.

2022-11-28 14:43 UTC, thraxil commented
@bryanlandia what's the status of this PR?

2024-06-26 17:36 UTC, closed without merging