Add all Tahoe installed XBlocks to course outline block_types_filter
appsembler/edx-platform pull request #898
Opened 2021-05-03 19:55 UTC by bryanlandia

Backport for Hawthorn.  DHIS2 is using Hawthorn Tahoe branch so we do still need this backported even though Juniper is in test.

2021-05-04 11:10 UTC, OmarIthawi requested changes

2021-05-04 11:10 UTC, OmarIthawi commented on openedx/features/course_experience/utils.py
> +        'pdf'
Thanks @bryanlandia. Would you mind making a setting of this change? Let's undo all Tahoe-specific changes and make it a setting.

This change will affect all of Juniper, Hawthorn and their devstacks, it's hard to coordinate between all of those in a hard-coded manner.

e.g. `TAHOE_BLOCK_TYPES_FILTER`

2021-05-09 19:40 UTC, bryanlandia commented
@OmarIthawi Updated to use an ENV_TOKEN setting.  I found that the course outline was reworked after Koa so we only need this until Lilac.

2021-05-09 19:42 UTC, bryanlandia commented
When merging this please merge also https://github.com/appsembler/edx-configs/pull/1083

2021-05-10 12:37 UTC, OmarIthawi commented
@bryanlandia please rebase over `appsembler/tahoe/develop` to fix the tests.

2021-05-14 19:58 UTC, bryanlandia commented
Rebased and tests passing, @OmarIthawi

2021-05-17 07:43 UTC, OmarIthawi approved these changes
Look great, thanks!

2021-05-18 18:47 UTC, merged