create appsembler api v2
appsembler/edx-platform pull request #967
Opened 2021-07-21 17:45 UTC by estherjsuh

## Change description

Create appsembler api v2

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2021-07-21 18:36 UTC, johnbaldwin commented on openedx/core/djangoapps/appsembler/api/v2/views.py
> +    @beeline.traced(name="apis.v1.views.CourseViewSet.get_queryset")
This is v2, right?

2021-07-21 18:39 UTC, johnbaldwin commented on openedx/core/djangoapps/appsembler/api/v2/views.py
> +"""Tahoe version 1 API views
v2

2021-07-21 18:42 UTC, johnbaldwin commented on openedx/core/djangoapps/appsembler/api/v2/views.py
> +from openedx.core.djangoapps.appsembler.api.v1.filters import (
Since v1 shouldn't change behavior, this is ok for v2, no need to duplicate v1 modules until there are changes, then I'd suggest only implementing changed classes/functions within new v2 modules. For example:
You find you need to update CourseEnrollmentFilter but not any other filters. Then create a v2/filters.py and only have CourseEnrollmentFilter redefined in there. This will likely help with maintainability because of reduced duplication and with readability as it will be easier to see what dependencies have changed from v1 to v2

2021-07-21 21:52 UTC, johnbaldwin commented on openedx/core/djangoapps/appsembler/api/v2/views.py
> +        - HttpResponse: 200 on success, {"user_id ": 9} -> {"user_id": 9}
Space in the key is a bug that I'd recommend get fixed in v1 as long as we can coordinate with customers

2021-07-22 00:05 UTC, estherjsuh commented
@johnbaldwin I slimmed the `v2` dir - I believe this is the minimum but please let me know if there is more to trim. Thanks!

2021-07-22 17:46 UTC, melvinsoft requested changes
@estherjsuh I added a comment with a suggested change.

2021-07-22 17:46 UTC, melvinsoft commented on openedx/core/djangoapps/appsembler/api/v2/views.py
> +class RegistrationViewSet(TahoeAuthMixin, viewsets.ViewSet):
@estherjsuh I think we could inherit directly from v1 RegistrationViewSet class here, in that case you only need to rewrite the `create` method and there is no need to copy the `_normalize_bool_param` for example.

```suggestion
class RegistrationViewSet(v1.views.RegistrationViewSet):
```

2021-07-22 18:27 UTC, estherjsuh commented on openedx/core/djangoapps/appsembler/api/v2/views.py
> +class RegistrationViewSet(TahoeAuthMixin, viewsets.ViewSet):
@melvinsoft I imported the `RegistrationViewSet` from v1, and updated v2 to:

- `class RegistrationViewSet(RegistrationViewSetV1):`

2021-07-26 17:26 UTC, OmarIthawi reviewed
I've added minor comments if we'd like to stick with this approach. However, for a small bug I think we're going to maintain a large set of code and the we'd need to deprecate and add tests.

We have two options and I'm leaning towards (B):

 A) Continue with the v1/v2 migration and give the customers time to migrate and the deprecate v1. We need v2 changes to have _automated tests_.

 B) Update the v1 in-place to include the following change:
    - Provide both `"user_id "` and `"user_id"` and inform customers to migrate from the `"user_id "` as it's a mistake.
     - Introduce a waffle flag to turn off `"user_id "` in the near future after we've communicated with customers

What do you think?

2021-07-26 17:26 UTC, OmarIthawi commented on openedx/core/djangoapps/appsembler/api/v2/api.py
> +from student.models import (
Please remove unused imports if any.

2021-07-28 12:20 UTC, OmarIthawi approved these changes
Thanks Esther. I've checke dthe code and it looks great please import `send_password_reset_email` and `create_password` to reduce code duplication.

2021-07-28 15:41 UTC, OmarIthawi approved these changes
Thanks Esther! I literally have no additional comments 😅.

Please test on staging and see if it works well. We'll have some documentation and customer communication work, please let me know if you need anything from me on that.

2021-07-28 16:05 UTC, merged