RED-2368: fix course grades for show_correctness == never
appsembler/edx-platform pull request #998
Opened 2021-09-01 15:43 UTC by estherjsuh

## Change description

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2021-09-01 16:28 UTC, OmarIthawi requested changes
Thanks @estherjsuh for tackling this intricate issue. Sorry for the late feedback but here's what I think we should do:

 - Keep this PR open and not merge it yet.
 - Revert: https://github.com/appsembler/edx-platform/pull/943 since it was a controversial change at the core of Open edX which we're not familiar with.
   * This will fix the newly introduced bug at the cost of bringing the old problem back
 - Create a new PR to fix the original problem at the caller (progress page) instead of editing the core.
 - Contribute the fix to edX for further review and that's because this fix is unrelated to Tahoe and we'd benefit a lot of an upstream review.

I'm so sorry again, that sounds like a lot of work. I'll explain why this makes sense even though we have a working PR:
 - The cost of maintaining this and its related PR are not small, and we'll be maintaining them for releases to come.
 - The two fixes contains test changes which are very prune to merge conflicts and we've had so many of those when we upgraded to Juniper -- I've took notes of the some of them here: https://gist.github.com/OmarIthawi/5fdb386c88708a61dd2b94aa6b15ff3a
 - Reverting the original fix #943 reduces the urgency of the problem and buy us some time.

Please let me know if there's anything I can do to make this easier.

2021-09-01 20:24 UTC, estherjsuh commented
@OmarIthawi thank you for explaining all that so thoroughly!
I am onboard with your suggested approach above. Let's regroup around next steps in jira: [RED-2368 ](https://appsembler.atlassian.net/browse/RED-2368)

2022-11-28 14:47 UTC, thraxil commented
@OmarIthawi with Esther gone, do we have someone else who's willing/able to drive this PR through? Or should we just cut our losses, close it out, and revisit after the nutmeg upgrade?

2022-11-29 08:36 UTC, OmarIthawi commented
I'm going to close it. Thanks for the reminder Anders.

If we get another report, we'll fix it.

2022-11-29 08:36 UTC, closed without merging